### ISSUE TITLE
Android source disconnects after we reply to GET_PARAMETER

### ISSUE THREAD

**Issue by jku** [01org/wysiwidi#39]
I'm not sure if this is because of updates to android or changes in our code but it does seem like Android source dislikes our GET_PARAMETERS reply: it seems to disconnect immediately after that.

Attaching RTSP exchange:
```
OPTIONS * RTSP/1.0
Date: Sun, 11 Jan 2015 15:18:20 +0000
Server: stagefright/1.2 (Linux;Android 5.0.1)
CSeq: 1
Require: org.wfa.wfd1.0

RTSP/1.0 200 OK
CSeq: 1
Public: org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER

OPTIONS * RTSP/1.0
CSeq: 1
Require: org.wfa.wfd1.0

RTSP/1.0 200 OK
Date: Sun, 11 Jan 2015 15:18:30 +0000
Server: stagefright/1.2 (Linux;Android 5.0.1)
CSeq: 1
Public: org.wfa.wfd1.0, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER

GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Sun, 11 Jan 2015 15:18:30 +0000
Server: stagefright/1.2 (Linux;Android 5.0.1)
CSeq: 2
Content-Type: text/parameters
Content-Length: 83

wfd_content_protection
wfd_video_formats
wfd_audio_codecs
wfd_client_rtp_ports
RTSP/1.0 200 OK
CSeq: 2
Content-Length: 302

wfd_audio_codecs: LPCM 00000003 00, AAC 0000000F 00, AC3 00000007 00
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 0 0 mode=play
wfd_content_protection: none
wfd_video_formats: 40 00 01 10 0001FFFF 1FFFFFFF 00000FFF 00 0000 0000 11 0000 0000, 02 10 0001FFFF 1FFFFFFF 00000FFF 00 0000 0000 11 0000 0000
```

**Comment by jku** [comment]
For reference: I'm testing with https://github.com/jku/wysiwidi/tree/p2p-new-connman-api -- No PR because it requires connman patches that are not upstream yet.

**Comment by kanavin** [comment]
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 0 0 mode=play

This is incorrect; the first zero should be the RTP port the sink is listening on.

**Comment by jku** [comment]
Ah the RTP port number is wrong in our reply.

**Comment by jku** [comment]
Right. MiracGstSink::sink_udp_port() works as expected but after this call:

    g_object_get(source, "port", &port, NULL);

port is still 0. It does not seem to be a gstreamer regression as I tried with an older version of wysiwidi and that seems to work -- at least the port is set correctly there.

**Comment by kanavin** [comment]
Can you run gst-test binary and see if it reports the sink listening port correctly on the same system? Do not specify a port on the command line.

**Comment by kanavin** [comment]
This one: https://github.com/01org/wysiwidi/blob/master/mirac_network/gst-test.cpp

**Comment by jku** [comment]
gst-test works fine. Strange.

**Comment by jku** [comment]
Now I see, it's getting the wrong hostname from somewhere (it's trying to listen on the remote ip)

**Comment by jku** [comment]
I've fixed this in my local branch by giving the GstSinkMediaManager the local host name (it was getting the remote one), thanks for help

**Comment by kanavin** [comment]
It's better to give GstSinkMediaManager an empty string, then the sink will listen for incoming RTP packets on both IPv4 and IPv6 sockets. On some systems 127.0.0.1 resolves to localhost, but localhost resolves to an IPv6 address.

**Comment by jku** [comment]
Sorry my comment was a bit ambiguous: I didn't mean "localhost" as in 127.0.0.1 but "local host": the actual ip address we have on the P2P link.

**Comment by kanavin** [comment]
Yeah, but still it's better not to give any hostname at all, just pass in "". 

So we protect ourselves against the situation when RTP packets start flowing to an IPv6 socket when we're listening on IPv4, or vice versa (has happened to me due to host resolution quirk I mentioned above).

**Comment by jku** [comment]
We get the hostname directly from the connection manager, I don't see how it could be wrong. What is the quirk that makes this happen?

**Comment by kanavin** [comment]
If the source resolves the sink's IPv4 address to a hostname, and then resolves the hostname back to IP address, it may end up with an IPv6 address. So the sink has to listen on both. The way to ensure that is to pass "" as the hostname.

**Comment by jku** [comment]
I've re-added the --hostname and --rtsp_port options to the sink (in case
they're still useful for debugging without P2P) and there I agree the
argument makes sense: I've made sure "" is used as local hostname whenever
the options are used.

But in the normal case where Wifi P2P is used, we know it's IPv4 (by
specification), and we know connman (as gateway, DHCP server and  group
owner) provides us with valid info -- I don't think there is a way to fail
there and don't see why we should host the service on all interfaces if we
can avoid it.

**Comment by kanavin** [comment]
That seems alright to me. When do you plan a pull request?

**Comment by jku** [comment]
Should be fixed now.
