### ISSUE TITLE
IOP: Netgear Push2TV sends SETUP without Request-URI

### ISSUE THREAD

**Issue by jku** [01org/wysiwidi#59]
Testing our source with the Netgear Push2TV sink we receive what seems to me like a malformed RTSP request (notice the missing Request-URI) and we just drop it. The earlier OPTIONS message does contain a Request-URI (but then again that one is just "*").

Relevant debug output from the source:
```
(desktop-source-test:6167): rtsp-DEBUG: Received RTSP message:
SETUP  RTSP/1.0
CSeq: 2
User-Agent: SEC-WDH/ME29
Transport: RTP/AVP/UDP;unicast;client_port=19000


Unknown message
Unknown message
Unknown message
Unknown message
Unknown message
Unknown message
Unknown message
Unknown message
Unknown message
```

**Comment by jku** [comment]
Earlier I said we respond to this message with 200 OK: that was incorrect, we do not respond (as is expected if the parser drops the packet).

**Comment by alexshalamov** [comment]
What should we do about that? I mean, we can fix parser and set empty resource URI. I wonder what kind of URI would be sent for PLAY request.

**Comment by jku** [comment]
I'm going to eavesdrop on android in the same case and report back -  just filed this so I don't forget

**Comment by jku** [comment]
I'm postponing this until the DHCP/GO debacle (see mailing list) is solved: there's a chance that is affecting this as well.

I can already say that Android does not trigger this behaviour: Netgear uses the correct Request-URI for them. Also modifying our presentation URI to really be a uri on the real source IP did not help: (that's still something we might want to do).

**Comment by jku** [comment]
Wow. Fixing the DHCP problems didn't help. Fixing the presentation url to include our real ip didn't help.

The real problem is that the Netgear parser is case sensitive. When I changed "wfd_presentation_url" to wfd_presentation_URL", it started working.

The spec clearly says everything except method names are insensitive... but we could make sure we always use the same capitalization as the spec does.
