### ISSUE TITLE
wfd_video_formats max-hres/max-vres are not "none" whan they should be

### ISSUE THREAD

**Issue by jku** [01org/wysiwidi#64]
desktop_source ends up sending this:

    SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
    CSeq: 3
    Content-Length: 209
    
    wfd_client_rtp_ports: RTP/AVP/UDP;unicast 19000 0 mode=play
    wfd_presentation_url: rtsp://127.0.0.1/wfd1.0/streamid=0 none
    wfd_video_formats: 00 00 01 01 00000001 00000000 00000000 00 0000 0000 00 0000 0000

I think wfd_video_formats is wrong: max-hres and max-vres values depend on the message they're in (yeah, crazy). In M4 request the values are always "none". In M3 response they are "none" if preferred-display-mode is not supported, and a 4*4hexdigit otherwise.

**Comment by alexshalamov** [comment]
PR #74 should fix it

**Comment by jku** [comment]
I think it won't fix this: the bug is not about the format choice, it's about the spec asking for really weird output differences in messages that I think we don't do. I'll fix the title to represent issue better
