### ISSUE TITLE
error when running connmand

### ISSUE THREAD

**Issue by ayoubayoub** [01org/wysiwidi#95]
Hi,
I'm running ubuntu 14.10 wpa_supplicant2.4 and connman 1.28, when I run the command sudo connmand -n -d I get this error : 

Failed to create storage directory: No such file or directory
Connection ":1.144" is not allowed to own the service "net.connman" due to security policies in the configuration file
Does anyone have idea about what's wrong because when googling it, I didn't find very useful answers ?

**Comment by jku** [comment]
These are connman issues so not really appropriate.

First one is connman failing to create /var/lib/connman/ so you're probably not root. Second one is D-Bus telling you you don't have the rights to own the service name on system bus: either you haven't installed the D-Bus policy file or you are not root.

**Comment by ayoubayoub** [comment]
@jku Firsteval I 'm very sorry to post this issue here but just I want a faster help by posting here.

I solved this problem by coping the file /connman1.28/src/connman-dbus.conf under /etc/systemd but when I run ./connmanctl I get this error : 

"Error getting services: Rejected send message, 3 matched rules; type="method_call", sender=":1.123" (uid=1000 pid=10342 comm="./connmanctl ") interface="net.connman.Manager" member="GetServices" error nameError getting peers: Rejected send message, 3 matched rules; type="method_call", sender=":1.123" (uid=1000 pid=10342 comm="./connmanctl ") interface="net.connman.Manager" member="GetPeers" error name="(unsError getting technologies: Rejected send message, 3 matched rules; type="method_call", sender=":1.123" (uid=1000 pid=10342 comm="./connmanctl ") interface="net.connman.Manager" member="GetTechnologies" error name="(unset)" requested_reply="0" destination="net.connman" (uid=0 pid=10332 comm="./connmand -n -d -c main.conf ")connmanctl> "

**Comment by kanavin** [comment]
@ayoubayoub If you insist on getting connman help here (especially when your reason is 'I want faster help'), you will not get any help at all. 

The proper channels to ask questions about connman are listed here: https://01.org/connman  - try either the IRC channel or the mailing list.
