### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by ayoubayoub** [01org/wysiwidi#96]
Hi, I'm testing wysiwidi and it seems that it is working but when I run the command G_MESSAGES_DEBUG=all ./sink-test a window is open and I get just a first picture from my android device and then it's blocked there and also no sound I can here from my desktop.
![capture du 2015-04-08 09 14 00](https://cloud.githubusercontent.com/assets/8190909/7041487/97d93942-ddd1-11e4-92ec-d0930ab4cb4e.png)

this is the output of G_MESSAGES_DEBUG=all ./sink-test : 
* Registering Wifi Display with IE 00000600111C440032
* New peer: Android_5e33
* Connecting to source at 192.168.0.2:7236
** Message: Trying to connect...
** Message: connection success to: 192.168.0.2
(sink-test:25424): rtsp-DEBUG: Received RTSP message:
OPTIONS * RTSP/1.0
Date: Wed, 08 Apr 2015 08:10:16 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 1
Require: org.wfa.wfd1.0

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 1
Public: org.wfa.wfd1.0, GET_PARAMETER, SET_PARAMETER

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
OPTIONS * RTSP/1.0
CSeq: 1
Require: org.wfa.wfd1.0

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
RTSP/1.0 200 OK
Date: Wed, 08 Apr 2015 08:10:16 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 1
Public: org.wfa.wfd1.0, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:10:16 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 2
Content-Type: text/parameters
Content-Length: 83

wfd_content_protection
wfd_video_formats
wfd_audio_codecs
wfd_client_rtp_ports

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 2
Content-Type: text/parameters
Content-Length: 306

wfd_audio_codecs: LPCM 00000003 00, AAC 0000000F 00, AC3 00000007 00
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 59528 0 mode=play
wfd_content_protection: none
wfd_video_formats: 40 00 02 10 0001FFFF 1FFFFFFF 00000FFF 00 0000 0000 00 none none, 01 10 0001FFFF 1FFFFFFF 00000FFF 00 0000 0000 00 none none

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:10:17 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 3
Content-Type: text/parameters
Content-Length: 246

wfd_video_formats: 00 00 02 02 00000020 00000000 00000000 00 0000 0000 00 none none
wfd_audio_codecs: AAC 00000001 00
wfd_presentation_URL: rtsp://192.168.0.2/wfd1.0/streamid=0 none
wfd_client_rtp_ports: RTP/AVP/UDP;unicast 59528 0 mode=play

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 3

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
SET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:10:17 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 4
Content-Type: text/parameters
Content-Length: 27

wfd_trigger_method: SETUP

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 4

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
SETUP rtsp://192.168.0.2/wfd1.0/streamid=0 RTSP/1.0
CSeq: 2
Transport: RTP/AVP/UDP;unicast;client_port=59528
Require: org.wfa.wfd1.0

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
RTSP/1.0 200 OK
Date: Wed, 08 Apr 2015 08:10:17 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 2
Session: 2105011384;timeout=30
Transport: RTP/AVP/UDP;unicast;client_port=59528;server_port=64512

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
PLAY rtsp://192.168.0.2/wfd1.0/streamid=0 RTSP/1.0
CSeq: 3
Session: 2105011384
Require: org.wfa.wfd1.0

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
RTSP/1.0 200 OK
Date: Wed, 08 Apr 2015 08:10:17 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 3
Session: 2105011384;timeout=30
Range: npt=now-

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:10:42 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 5
Session: 2105011384

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 5

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:11:07 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 6
Session: 2105011384

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 6

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:11:32 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 7
Session: 2105011384

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 7

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:11:57 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 8
Session: 2105011384

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 8

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:12:22 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 9
Session: 2105011384

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 9

(sink-test:25424): rtsp-DEBUG: Received RTSP message:
GET_PARAMETER rtsp://localhost/wfd1.0 RTSP/1.0
Date: Wed, 08 Apr 2015 08:12:47 +0000
Server: stagefright/1.2 (Linux;Android 4.4.2)
CSeq: 10
Session: 2105011384

(sink-test:25424): rtsp-DEBUG: Sending RTSP message:
RTSP/1.0 200 OK
CSeq: 10

  any help please ?

**Comment by kanavin** [comment]
Your gstreamer is out of date. README.md says which version you need to have - you pretty much have to build it from git checkout right now because they haven't yet released a version with a fix.
